# Generated by Django 6.0.4 on 2026-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id_contratto', models.AutoField(db_column='idContratto', primary_key=True, serialize=False)),
                ('data_stipula', models.TextField(blank=True, null=True)),
                ('costo_totale', models.FloatField()),
                ('cauzione_importo', models.FloatField()),
                ('cauzione_stato', models.TextField()),
                ('cauzione_data_pagamento', models.TextField(blank=True, null=True)),
                ('saldo_importo', models.FloatField()),
                ('saldo_stato', models.TextField()),
                ('saldo_data_pagamento', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Contratto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id_prenotazione', models.AutoField(db_column='idPrenotazione', primary_key=True, serialize=False)),
                ('tipo_ritiro', models.TextField()),
                ('indirizzo_ritiro', models.TextField()),
                ('data_inizio', models.TextField()),
                ('data_fine', models.TextField()),
                ('stato', models.TextField()),
                ('costo_previsto', models.FloatField()),
                ('cauzione_richiesta', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Prenotazione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.AutoField(db_column='idStaff', primary_key=True, serialize=False)),
                ('ruolo', models.TextField()),
                ('stipendio', models.FloatField()),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id_utente', models.AutoField(db_column='idUtente', primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cognome', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True, unique=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'Utente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id_veicolo', models.AutoField(db_column='idVeicolo', primary_key=True, serialize=False)),
                ('marca', models.TextField()),
                ('modello', models.TextField()),
                ('colore', models.TextField()),
                ('prezzo_giornaliero', models.FloatField()),
                ('stato', models.TextField()),
                ('tipo', models.TextField()),
                ('cambio', models.TextField(blank=True, null=True)),
                ('cabrio', models.IntegerField()),
                ('targa', models.TextField(blank=True, null=True)),
                ('cilindrata', models.IntegerField(blank=True, null=True)),
                ('batteria_watt', models.IntegerField(blank=True, null=True)),
                ('lunghezza', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Veicolo',
                'managed': False,
            },
        ),
    ]
